name: Deploy Angular Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: ng build --configuration production

      - name: Deploy to build branch
        run: |
          # Nos movemos a la carpeta del build
          cd dist
          app_name=$(ls)  # nombre del proyecto dentro de dist
          cd $app_name

          # Inicializamos un nuevo repo temporal para la rama build
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # Creamos y subimos la rama build
          git checkout -b build
          git add .
          git commit -m "🚀 Deploy build from commit ${{ github.sha }}"
          git push --force origin build
